### ISSUE TITLE
Tips for fresh bird

### ISSUE THREAD

**Issue by joddiy** [sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B#1]
Tips for a fresh bird like me,  after installing the wheel, you may encounter such error:
```
ImportError: libopenblas.so.0
```
just install the Openblas like this:
```
sudo apt install libopenblas-dev
```

**Comment by mhrahimi** [comment]
I'm getting the following error on raspbian on RaspPi4b:
ERROR: torchvision-0.5.0a0+9cdc814-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.

**Comment by sungjuGit** [comment]
As we noted, please check out the detailed instructions (some contents might be outdated by now)

https://sites.google.com/view/steam-for-vision/raspberry-pi/PytorchRP4
