### ISSUE TITLE
Do you have plans to release aarch64 version?

### ISSUE THREAD

**Issue by patrickj-fd** [sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B#2]
RT.

**Comment by sungjuGit** [comment]
We haven't had a chance to move to a 64bit OS.  Maybe later in 2021 when the native 64-bit OS matures (Sorry for the late response.  We have not been active with this project for quite a while).

**Comment by sungjuGit** [comment]
We have decided to wait for Raspberry 5 before revisiting the issue of migrating to a 64-bit OS.  If others have already created wheels, please feel free to announce them here.
