### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute 'bitwise_xor_'

### ISSUE THREAD

**Issue by AbhishekPokala** [sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B#3]
## Description
Built Torch 1.4.0 from the wheel provided in this repository but it throws an AttributeError for the bitwise_xor_ function, which is supported by the official release of Torch 1.4.0.
Can anyone help me understand why this happening?

**Comment by sungjuGit** [comment]
It does not appear that anybody visiting this repository had any good suggestion.  Since newer versions of PyTorch have already been released,  I am closing this issue.
