### ISSUE TITLE
not a supported wheel on this platform

### ISSUE THREAD

**Issue by mhrahimi** [sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B#5]
I'm getting the following error on raspbian on RaspPi4b:
ERROR: torchvision-0.5.0a0+9cdc814-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.

**Comment by sungjuGit** [comment]
Are you trying to install PyTorch 1.4.0 (our original version) or a later version?  If a later version, then please direct all inquiries to a particular contributor (I believe someone with ID name CW-B-W for 1.8).  

BTW, did you follow all the instructions in
https://sites.google.com/view/steam-for-vision/raspberry-pi/PytorchRP4
